###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

networks:
  dasha_network:
    external:
      name: plains_network

services:
    plains-nginx:
      image: nginx:alpine
      container_name: plains-nginx
      hostname: plains-nginx
      working_dir: /var/www
      volumes:
        - ./src:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./docker/var/log:/var/log/nginx
      ports:
        - "8090:80"
      networks:
        dasha_network:
          aliases:
            - plains-nginx

    plains-php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      container_name: plains-php
      hostname: plains-php
      working_dir: /var/www/
      volumes:
        - ./src:/var/www
        - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/99-overrides.ini
        - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
        - ./docker/var/.bash_history:/root/.bash_history
        - ./docker/var/log:/var/log/php
        - ~/.ssh:/root/.ssh
      environment:
        XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
        PHP_IDE_CONFIG: "serverName=dasha-docker"
        APP_ENV: "development"
      networks:
        dasha_network:
          aliases:
            - plains-php
